debug : False  
exp_name : finetune_fetal
project_name : lotus-Segmentation     
base_folder_data_path: datasets/CT_labelmaps_fetal/
base_folder_mask_path : datasets/CT_labelmaps_fetal/
labelmap_path : /ct_labelmap/
aorta_only: False

data_dir_real_us_cut_training : datasets/trainA_500_fetal
output_path : ./checkpoints
device : cuda

seg_network_ckpt: checkpoints/best_checkpoint_seg_renderer_valid_loss_335_exp_name13_5e-06_0.0001_0.0001_epoch=1.pt
cut_network_ckpt: checkpoints/best_checkpoint_CUT_val_loss_335_exp_name13_5e-06_0.0001_0.0001_epoch=1.pt

dataset : ct_3d_labemaps_dataset.CT3DLabelmapDataset
dataloader_ct_labelmaps : ct_3d_labemaps_dataset.CT3DLabelmapDataLoader

module : segm_us_rendr.SegmentationUSRenderedModule

outer_model_monai : False
outer_model : unet_2d.OriginalUNet

dropout: False
dropout_ratio : 0.0
seg_net_input_augmentations_noise_blur : True
seg_net_input_augmentations_rand_crop : True

inner_model : us_rendering_model.UltrasoundRendering
warp_img : True
num_workers : 8

n_classes : 1
pred_label : 13

batch_size : 1
inner_model_learning_rate: 0.0001
outer_model_learning_rate: 0.0001
scheduler : False
grad_clipping: False

min_epochs : 0
max_epochs : 200
early_stopping_patience : 0 #5
validate_every_n_steps : 1 #default is 50

stopping_crit_gt_imgs : False
epochs_check_stopp_crit : 0

use_idtB : False
logging : True
log_default_renderer : True
nr_imgs_to_plot : 16

